# ============================================================================
# Nexus — Pydantic V2 Models
# Serves: ALL agents — shared data models for vendor state, checklist,
#         verification results, audit log, and the complete workflow state.
# ============================================================================

from __future__ import annotations

import uuid
from datetime import datetime
from enum import Enum
from typing import Any, Optional

from pydantic import BaseModel, Field


# ── Enums ──────────────────────────────────────────────────────────────────

class WorkflowStatus(str, Enum):
    """Tracks the overall workflow lifecycle."""
    PENDING = "pending"
    ACTIVE = "active"
    STALLED = "stalled"
    ESCALATED = "escalated"
    COMPLETE = "complete"
    HALTED = "halted"  # fraud signal → immediate stop


class DocumentStatus(str, Enum):
    """Status of an individual document in the checklist."""
    PENDING = "pending"
    SUBMITTED = "submitted"
    VERIFIED = "verified"
    FAILED = "failed"
    EXPIRED = "expired"
    FRAUD_SUSPECT = "fraud_suspect"
    RE_REQUESTED = "re_requested"


class RiskLevel(str, Enum):
    """Risk score levels for a vendor."""
    LOW = "Low"
    MEDIUM = "Medium"
    HIGH = "High"


class HealthStatus(str, Enum):
    """Post-approval vendor health status."""
    GREEN = "Green"
    AMBER = "Amber"
    RED = "Red"


class EscalationLevel(int, Enum):
    """Three-level error recovery escalation."""
    NONE = 0
    AUTO_RETRY = 1
    REROUTE = 2
    HUMAN = 3


# ── Checklist Models ───────────────────────────────────────────────────────

class ChecklistItem(BaseModel):
    """A single compliance checklist item generated by the Orchestrator."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4())[:8])
    category: str = Field(..., description="e.g. Legal, Financial, Regulatory, Quality")
    document_name: str = Field(..., description="Name of the required document")
    description: str = Field(default="", description="What this document proves")
    required: bool = Field(default=True)
    status: DocumentStatus = Field(default=DocumentStatus.PENDING)
    retry_count: int = Field(default=0, description="Number of collection retries")
    max_retries: int = Field(default=2)


# ── Verification Models ───────────────────────────────────────────────────

class VerificationResult(BaseModel):
    """Result of verifying a single document against APIs."""
    doc_name: str
    status: DocumentStatus
    reason: str = ""
    expiry_date: Optional[str] = None
    cert_number: Optional[str] = None
    api_source: Optional[str] = None  # which API was checked
    cross_reference_match: Optional[bool] = None  # cert# matches API?
    verified_at: datetime = Field(default_factory=datetime.utcnow)


class FraudFlag(BaseModel):
    """A fraud signal detected during verification."""
    doc_name: str
    flag_type: str = Field(..., description="e.g. cert_mismatch, expired_forgery, sanctioned_entity")
    description: str
    severity: str = Field(default="high", description="low / medium / high / critical")
    detected_at: datetime = Field(default_factory=datetime.utcnow)


# ── Audit Models ──────────────────────────────────────────────────────────

class AuditLogEntry(BaseModel):
    """Every agent decision is logged with timestamp and reason."""
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    agent: str = Field(..., description="Which agent performed the action")
    action: str = Field(..., description="What was done")
    reason: str = Field(default="", description="Why it was done")
    details: dict[str, Any] = Field(default_factory=dict)


class ExceptionItem(BaseModel):
    """An item that needs human review or escalation."""
    id: str = Field(default_factory=lambda: str(uuid.uuid4())[:8])
    exception_type: str = Field(..., description="e.g. missing_doc, verification_failure, fraud_signal")
    description: str
    agent: str = Field(..., description="Agent that raised the exception")
    requires_human: bool = Field(default=False)
    resolution: Optional[str] = None
    created_at: datetime = Field(default_factory=datetime.utcnow)


# ── Vendor Request (Buyer Input) ──────────────────────────────────────────

class VendorRequest(BaseModel):
    """The buyer's initial request to onboard a new vendor."""
    vendor_name: str = Field(..., description="Name of the supplier company")
    industry: str = Field(..., description="e.g. MedTech, IT, Finance, Pharma, Manufacturing")
    contact_email: str = Field(default="")
    urgency: str = Field(default="normal", description="normal / urgent / critical")
    notes: str = Field(default="")


# ── Shared Vendor State (The Core) ────────────────────────────────────────

class VendorState(BaseModel):
    """
    The shared state object that ALL agents read from and write to.
    This is the single source of truth for a vendor's verification workflow.
    Matches the spec's shared agent state schema exactly.
    """
    model_config = {"use_enum_values": True}

    # Identity
    vendor_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    vendor_name: str = ""
    industry: str = ""
    contact_email: str = ""

    # Checklist (generated by Orchestrator)
    checklist: list[ChecklistItem] = Field(default_factory=list)

    # Documents (tracked by Collector)
    documents_submitted: dict[str, str] = Field(
        default_factory=dict,
        description="filename → status mapping"
    )
    documents_pending: list[str] = Field(default_factory=list)

    # Verification (performed by Verifier)
    verification_results: dict[str, VerificationResult] = Field(
        default_factory=dict,
        description="doc_name → verification result"
    )

    # Fraud detection
    fraud_flags: list[FraudFlag] = Field(default_factory=list)

    # Risk assessment (computed by Risk Scorer)
    risk_score: Optional[RiskLevel] = None
    risk_rationale: str = ""

    # Audit trail (maintained by all agents, compiled by Audit Agent)
    audit_log: list[AuditLogEntry] = Field(default_factory=list)

    # Workflow control
    workflow_status: WorkflowStatus = Field(default=WorkflowStatus.PENDING)
    exceptions: list[ExceptionItem] = Field(default_factory=list)
    current_step: int = Field(default=0)
    escalation_level: EscalationLevel = Field(default=EscalationLevel.NONE)

    # Monitoring (post-approval, managed by Monitor Agent)
    health_status: Optional[HealthStatus] = None
    last_monitored: Optional[datetime] = None
    monitoring_notes: str = ""

    # Timestamps
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)


# ── API Response Model ────────────────────────────────────────────────────

class NexusResponse(BaseModel):
    """Standard API response format: status, data, agent_actions_taken, timestamp."""
    status: str = "success"
    data: Any = None
    agent_actions_taken: list[str] = Field(default_factory=list)
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    message: str = ""
